// components/layout.tsx
import { Button, Row } from "antd";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { ReactNode } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface LayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Row>
        <ul>
          <li>
            <Link href="/"> Home</Link>
          </li>
          <li>
            <Link href="about"> About</Link>
          </li>
        </ul>
      </Row>
      <div>
        {/* Your layout content */}
        {children}
      </div>
    </>
  );
};

export default RootLayout;
